### ISSUE TITLE
could u provide checkpoint？

### ISSUE THREAD

**Issue by GGcaesar** [JialeTao/MoTrans#3]
Thanks for your exciting work, for studying can u provide the checkpoint for FOMM on the TED-talk?
(in your paper's Qualitative comparisons)
Thanks a lot!

**Comment by JialeTao** [comment]
baiduyun:https://pan.baidu.com/s/1Cljz7VVtm3P9wsv5zw2hew  passwd:2ck2
Currently I'm not sure that the state dict is strictly corresponded to the original FOMM repo. But I remember it would be slight if there exist difference. You can also train the FOMM code personally if it doesn't work.

**Comment by GGcaesar** [comment]
Thanks!!!
