### ISSUE TITLE
a issue about demo

### ISSUE THREAD

**Issue by Explore008** [JialeTao/MoTrans#5]
You have done a great job! But when I tried to run the demo file, I encountered an error that was displayed as' load '_ A parameter is missing from checkpoint. Could you please tell me how to solve it? Thank you!
![1692270938623](https://github.com/JialeTao/MoTrans/assets/111834651/6c30f20d-fef1-4cbc-ba01-af9bce9c8223)

**Comment by JialeTao** [comment]
Hi @Explore008 , this may be caused by the lib version of "yaml". using the command "yaml.load(file, Loader=yaml.FullLoader)" may helps.

**Comment by Explore008** [comment]
> Hi @Explore008 , this may be caused by the lib version of "yaml". using the command "yaml.load(file, Loader=yaml.FullLoader)" may helps.
Thank you for your reply! Your help is very effective, but when I drive the image character by loading the pre-trained taichi model, it produces great distortion and confusion, unlike a person. I wonder what caused it. Perhaps it is the clarity of the video and the pixel size of the image? I would appreciate it if you could provide a suitable video.

https://github.com/JialeTao/MoTrans/assets/111834651/72fb527e-e6cd-45e9-8057-45b118ada1bd


https://github.com/JialeTao/MoTrans/assets/111834651/d405b752-fed1-4835-b4c2-7bbf7a8f1634

**Comment by JialeTao** [comment]
The image and video size may not influence. This may be caused by the inability of the motion estimator for cross-domain motion estimation. To verify this and for better understanding, you could visualize the motion masks and keypoints of the driving video and source image.

**Comment by Explore008** [comment]
> 图像和视频大小可能不会影响。这可能是由于运动估计器无法进行跨域运动估计造成的。为了验证这一点并更好地理解，您可以可视化驾驶视频和源图像的运动遮罩和关键点。

Sorry,I can not find this problem.I want to experiment with taichi data set to see your excellent scientific research results. However, the download link of this file is wrong and the data is too large to load easily. Can you give me a copy that you have handled? I found your github email, but its domain name is not available. If you can, you can share it with my academic mailbox, 202233374@stumail.nwu.edu.cn. Thank you very much!

**Comment by JialeTao** [comment]
You can send an email to me (jialetao.std@gmail.com) and comment on your academic purpose, then I can share a copy of the dataset.

**Comment by Explore008** [comment]
> You can send an email to me ([jialetao.std@gmail.com](mailto:jialetao.std@gmail.com)) and comment on your academic purpose, then I can share a copy of the dataset.

I had sent a message to your email, but this message is refused  by your service.

**Comment by JialeTao** [comment]
Done it.

> > You can send an email to me ([jialetao.std@gmail.com](mailto:jialetao.std@gmail.com)) and comment on your academic purpose, then I can share a copy of the dataset.
> 
> I had sent a message to your email, but this message is refused by your service.
